# Лабораторная 0 - numpy
## Ответы на контрольные вопросы
Владимир Кирилкин ПИ18-2

In [63]:
import numpy as np

Какое свойство содержит количество элементов массива по измерениям?

In [69]:
arr = np.array([i for i in range(10)])
arr.shape

(10,)

Напишите функцию, создающую ndarray из массива [0, 1, 2, 3, 4]

In [70]:
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

Как создать нулевой 4-мерный вектор?

In [71]:
np.zeros([0 for _ in range(4)])

array([], shape=(0, 0, 0, 0), dtype=float64)

Как создать единичную диагональную матрицу 3х4

In [72]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

Сколько операций умножения матриц существует в numpy?

In [73]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B)       # прямое умножение
print(A @ B)      # математическое умножение
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


Напишите инструкцию, выбирающую каждый третий элемент массива А начиная с 10-го и заканчивая 45-м

In [74]:
np.array(np.arange(50))[10:45][::3]

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43])

Напишите инструкцию создания матрицы 4х3 из плоского массива из 12 элементов

In [75]:
np.array(np.arange(12)).reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])